name: njsscan
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.12'
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'
    - name: send curl
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"key1": "value1", "key2": "value2"}' http://pgr71bjwl06ea896iw29g.appsecengineer.training:8880/callback
